variables:
  PLATFORM_MIN_VERSION: 'trunk'
  MIGRATION_ASSISTANT_BRANCH: 'trunk'
  PLUGIN_DEPENDENCIES:
    value: >
      [
        { "name": "SwagMigrationAssistant", "url": "gitlab.shopware.com/shopware/6/services/migration-assistant", "branch": "$MIGRATION_ASSISTANT_BRANCH" }
      ]

include:
  project: 'shopware/6/product/platform'
  ref: 'trunk'
  file: '.gitlab/templates/plugin.yml'

Danger:
  stage: test
  image:
    name: ghcr.io/shyim/danger-php:latest
    entrypoint: [""]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  before_script: []
  script:
    - danger ci

ecs:
  stage: test
  script:
    - composer ecs

phpunit:
  services:
    - name: $MYSQL_IMAGE
      alias: database
      entrypoint: [ 'sh', '-c', "docker-entrypoint.sh $MYSQL_CMD" ]
  script:
    - composer dump-autoload --dev -d "${PROJECT_ROOT}/custom/plugins/${PLUGIN_NAME}"
    - php
      -d pcov.enabled=1 -d pcov.directory=$PWD/src -d pcov.exclude='~(vendor|tests|node_modules)~'
      ${PROJECT_ROOT}/vendor/bin/phpunit
      --configuration phpunit.xml.dist
      --log-junit ${CI_PROJECT_DIR}/phpunit.junit.xml
      --colors=never
      --coverage-cobertura ${CI_PROJECT_DIR}/cobertura.xml
      --coverage-text | grep -v -E '^Shopware\\|^  Methods:' # do not output covered files lines
  parallel:
    matrix:
      - MYSQL_IMAGE:
          - mysql:8.0
        DEV_IMAGE: [ 'shopware/development:8.2-composer-2', 'shopware/development:8.3-composer-2' ]
        MYSQL_CMD: $MYSQL8_CMD
        PLATFORM_BRANCH: [ $PLATFORM_MIN_VERSION ]
      - MYSQL_IMAGE:
          - mariadb:10.11
        DEV_IMAGE: [ 'shopware/development:8.2-composer-2', 'shopware/development:8.3-composer-2' ]
        PLATFORM_BRANCH: [ $PLATFORM_MIN_VERSION ]
        RUN_IN_MR: 'false'

phpstan:
  script:
    - composer phpstan
